### ISSUE TITLE
[BUG] Inconsistent treatment of non-required schemas?

### ISSUE THREAD

**Issue by dvv** [zoedsoupe/peri#8]
**Describe the bug**
Inconsistent treatment of non-required schemas?

**To Reproduce**
```ex
# nothing's required, why error?
validate(%{x: %{y: :string}}, %{})
{:error,
 [
   %Peri.Error{
     path: [:x],
     key: :x,
     content: %{actual: "nil", expected: %{y: :string}},
     message: "expected type of %{y: :string} received nil value",
     errors: nil
   }
 ]}

# naive workaround, inevident
validate(%{x: {:oneof, [%{y: :string}]}}, %{})
{:ok, %{}}
```

**Expected behavior**
A more consistent behavior.
AFAICS something like below might be applied

```
required?  nullable?   check
-------
0               0           data.has_key(k) && data[k] is T
0               1           data.has_key(k) && (data[k] is T or data[k] === nil)
1               0           data.has_key(k) and data[k] is T
1               1           data.has_key(k) and (data[k] is T or data[k] === nil)
```

**Comment by zoedsoupe** [comment]
i don't think so... if you're defining a nested schema you're declaring that the data need to match at least the nest level definition. it seems so strange to define a schema like

```ex
schema = %{x: %{y: :string}}
```

and `Peri.validate schema, %{}` return success... However, this makes a more sense:

```ex
Peri.validate %{x: %{y: :string}}, %{x: %{y: nil}}
# {:ok, %{x: %{y: nil}}}
```

some special schema definition are treated as required by default in order to match the semantic definition of schema. These are:
- `:cond`
- nested schemas
- `:dependent`

**Comment by dvv** [comment]
Well I see.

How do I express an optional attribute `x` being a list of nested schema `%{id: :string}`?
So that
```ex
%{}
%{x: []}
%{x: [%{id: "..."}]}
```
would be ok, but
```ex
%{x: nil}
%{x: [%{bebebe: "..."}]}
```
wouldn't?

TIA
